"""Users

Revision ID: 73464a876d18
Revises: bced6977d0cf
Create Date: 2023-07-06 19:07:44.867818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73464a876d18'
down_revision = 'bced6977d0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(length=32), nullable=False),
    sa.Column('first_name', sa.Text(length=32), nullable=False),
    sa.Column('last_name', sa.Text(length=32), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
